stages:
    - deploy


deploy_staging:
    image: max107/alpine-fabric3
    stage: deploy
    script:
        - fab staging deploy
    environment:
        name: develop
        url: http://les-brevno.ru
    only:
        - develop
