<?php

namespace App\Application\Sonata\UserBundle\Entity;

use App\Entity\ProductOrder;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

//    /**
//     * @ORM\OneToMany(targetEntity="App\Entity\ProductOrder", mappedBy="user")
//     */
//    private $orders;
//
//    public function __construct()
//    {
//        parent::__construct();
//        $this->orders = new ArrayCollection();
//        // your own logic
//    }

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

//    /**
//     * @return Collection|ProductOrder[]
//     */
//    public function getOrders(): Collection
//    {
//        return $this->orders;
//    }
//
//    public function addOrder(ProductOrder $order): self
//    {
//        if (!$this->orders->contains($order)) {
//            $this->orders[] = $order;
//            $order->setUser($this);
//        }
//
//        return $this;
//    }
//
//    public function removeOrder(ProductOrder $order): self
//    {
//        if ($this->orders->contains($order)) {
//            $this->orders->removeElement($order);
//            // set the owning side to null (unless already changed)
//            if ($order->getUser() === $this) {
//                $order->setUser(null);
//            }
//        }
//
//        return $this;
//    }
}
