<?php
/**
 * Created by IntelliJ IDEA.
 * User: kirillrossokhin
 * Date: 07.09.2018
 * Time: 11:44
 */

namespace App\Admin;

use App\Entity\FormRequest;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Route\RouteCollection;
use Sonata\AdminBundle\Show\ShowMapper;

class FormRequestAdmin extends AbstractAdmin
{
    protected function configureListFields(ListMapper $list)
    {
        $list
            ->addIdentifier('id')
            ->add('name', null, [
                'label' => 'Имя',
            ])
            ->add('phone', null, [
                'label' => 'Телефон',
            ])
            ->add('form_name', null, [
                'label' => 'Форма',
            ])
            ->add('message', null, [
                'label' => 'Сообщение',
            ])
            ->add('file', null, [
                'label' => 'Файл',
            ])
            ->add('created_at', null, [
                'label' => 'Создано',
            ])
        ;
    }

    protected function configureShowFields(ShowMapper $show)
    {
        $subject = $this->getSubject();

        $show
            ->add('name', null, [
                'label' => 'Имя',
            ])
            ->add('phone', null, [
                'label' => 'Телефон',
            ])
            ->add('form_name', null, [
                'label' => 'Форма',
            ])
            ->add('message', null, [
            'label' => 'Сообщение',
            ])
            ->add('file', null, [
                'label' => 'Файл',
                'template' => 'bundles/SonataAdminBundle/fileURL.html.twig',
            ])
            ->add('created_at', null, [
                'label' => 'Создано',
            ]);
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
    }

    protected function configureRoutes(RouteCollection $collection)
    {
        $collection
            ->remove('edit')
            ->remove('create');
    }

    public function toString($object)
    {
        return $object instanceof FormRequest
            ? $object->getFormName()
            : 'Заявка';
    }

}
